### ISSUE TITLE
Specify CSV delimiter

### ISSUE THREAD

**Issue by albertvisuals** [statamic/importer#23]
### Description

It seems that the CSV delimiter is currently hardcoded as "," 
All my CSVs are using ";" as a delimiter. 
It would be great if I can choose the delimiter of the CSV file within the import process. 
Thanks!

**Comment by duncanmcclean** [comment]
Are you able to provide an example of the CSV you're trying to import? 

I've just tried to import a CSV with a `;` delimiter and it worked without any issues. 🤔
