### ISSUE TITLE
How to: Add more than on handle to a custom transformer?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/importer#34]
### Description

I'm using this `ResourcesBard` transformer, it works for importing text into `resources_intro`.

How do I handle a second (or third) bard field type? I have a second bard fieldtype with the handle `resources_bard_sets`, which uses sets. 

How would I add it to the `ResourcesBard` transformer with a fallback to  return parent::transform($value); if neither bard handles exist?

```php

namespace App\ImportTransformers;

use Statamic\Importer\Transformers\AbstractTransformer;

class ResourcesBard extends AbstractTransformer
{
    public function transform($value)
    {
        $fieldHandle = $this->field->handle();

        if ($this->field->handle() !== 'resources_intro') {
            // Fallback to parent transformer
            return parent::transform($value);
        }

        // For resources_intro field, decode the JSON and extract post_intro
        $data = json_decode($value, true);
        
        // Return properly structured Bard field data
        return [
            [
                'type' => 'paragraph',
                'content' => [
                    [
                        'type' => 'text',
                        'text' => $data['post_intro']['raw']
                    ]
                ]
            ]
        ];
    }
}
```

**Comment by jasonvarga** [comment]
I might be misunderstanding the question, but maybe you need this?

```php
if (! in_array($this->field->handle(), ['resources_intro', 'resources_bard_sets'])) {
```

**Comment by duncanmcclean** [comment]
Just to clarify, you're wanting `resources_intro` and `resources_bard_sets` to fallback to the built-in Bard transformer?

**Comment by duncanmcclean** [comment]
Going to close this for now - assuming that's what you're meaning.

If it's not, feel free to clarify and we can re-open this isuse.
