### ISSUE TITLE
Minimise import for testing?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/importer#43]
### Description

Would it be possible to add an option to specify how many rows to import from a CSV?

Currently, I maintain two versions of my CSV file: a full export and a smaller, trimmed version. It would be much more convenient to manage just one file and have the importer allow me to define how many rows to import—for example, the first X rows or even specific rows.

This feature would be especially helpful as my import includes various types of data, with some rows containing fields that others do not. Having this flexibility would streamline the process.

**Comment by duncanmcclean** [comment]
Great idea!

However, I'm cautious of adding too many features that aren't needed by the majority of developers using the importer. For that reason, I'm going to close this issue.

We may reconsider this feature in the future if others need it.
