### ISSUE TITLE
Ability to update the upload file to reimport updated data (or provide an import template that could be applied to new imports)

### ISSUE THREAD

**Issue by avocadesign** [statamic/importer#8]
### Description

Love the new importer. One need that we have on lots of websites is to semi regularly import new content into a collection. 

It would be great if you could save the mapping you've setup and run that as a new import with an updated file. That could be done in one of two ways in the UI:

1. Save the imports that have run (which you're already doing with the recent imports section) and allow you to upload a new file into the import. This would pickup the the mapping you have and allow an new import
2. Allow the saving of the mapped fields as an import template that could be applied to a newly uploaded file. 

One thing this would also need to consider is whether to update or ignoring existing content. 

We use this type of functionality to semi regularly upload batch files of Honey batch tests, lake research data, publications and data like that from spreadsheets that clients compile with fixed columns  that don't change so remapping it each time would be very time consuming. Sometime there are a LOT of fields as well.

**Comment by duncanmcclean** [comment]
Good idea! I'll have a think about the best way to approach this.

> One thing this would also need to consider is whether to update or ignoring existing content.

I've created a separate feature request for this: #9
